config/routes.rb
require "sidekiq/web"
require 'sidekiq/cron/web'
require "user_constraint"

Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq", constraints: UserConstraint.new
  root to: "servers#index"

  get "welcome" => "onboarding#index", as: "welcome"
  post "welcome" => "onboarding#create"
  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create"
  get "two_factor" => "two_factor_auths#new", as: "two_factor"
  post "two_factor" => "two_factor_auths#create"
  delete "logout" => "sessions#destroy", as: "logout"

  resources :user_activation, only: [:edit, :update]
  resources :users, only: [:index, :create, :destroy] do
    collection do
      resource :two_step_verification, only: [:new, :create, :show, :destroy], module: "users"
    end
    post :resend_activation_mail, on: :member
  end

  resources :servers, only: [:create, :show, :destroy] do
    get :test_ssh, on: :member
    get :check_installation, on: :member
    get :updating, on: :member
    get :manual_update, on: :member
    post :start_installation, on: :member
    post :start_update, on: :member
    resource :health_check, only: [:create]
    resources :apps, only: [:index, :new, :create, :destroy, :show] do
      resources :services, controller: "app_services", only: :index do
        post :create, on: :member
      end
      resources :env_vars, only: [:index, :create, :destroy]
      resources :domains, only: [:index, :create, :destroy]
      resources :backups, only: [:index, :create] do
        post :enable, on: :collection
        get :status, on: :member
      end
    end
    resources :services, only: [:index] do
      post :create, on: :member
      get :status, on: :member
    end
    resources :deploy_keys, only: [:index, :new, :create, :destroy]
  end

  # Help
  get 'help'                  => 'help#index'
  get 'help/:category/:file'  => 'help#show', as: :help_page, constraints: { category: /.*/, file: /[^\/\.]+/ }

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/services_controller.rb
class ServicesController < ServerBaseController
  def index
    @server = Server.find(params[:server_id])
    @available_services = Service.where(active: true).order(name: :asc)
    @services = @server.services
  end

  def create
    server = Server.find(params[:server_id])
    service = Service.find(params[:id])
    server.services << service unless server.services.include?(service)
    AddServiceToServerJob.perform_later(server, service)
    redirect_to server_services_path(server)
  end

  def status
    @server = Server.find(params[:server_id])
    @service = Service.find(params[:id])
  end
end

app/views/services/_service.html.erb
<%= content_tag :div, id: dom_id(service), class: "service" do %>
  <div class="box <%= "service-#{server.service_status(service)}" %>">
    <h3 class="subtitle"><%= service.name %></h3>
    <p class="has-text-centered">
      <%= image_tag "services/#{service.name.downcase}.png", width: 100, height: 100 %>
    </p>
    <p class="has-text-centered <%= "is-hidden" unless server.service_status(service) == "installed" %>" data-service-status="installed">
      <span class="tag is-success">Installed</span>
    </p>
    <p class="has-text-centered <%= "is-hidden" unless server.service_status(service) == "installing" %>" data-service-status="installing">
    <span class="tag is-warning">Installing</span>
    </p>
    <p class="has-text-centered <%= "is-hidden" unless server.service_status(service) == "new" %>" data-service-status="new">
      <%= link_to "Install #{service.name}", server_service_path(server, service), method: :post, class: "button is-primary" %>
    </p>
  </div>
<% end %>

<script>
<% if server.service_status(service) == "installing" %>
  new ServerPoller("<%= status_server_service_path(server, service) %>").poll();
<% end %>
</script>

app/views/services/index.html.erb
<%= render "servers/heading", server: @server, tab: "services" %>
<div class="services">
  <% @available_services.each_slice(4).each do |service| %>
    <div class="columns">
      <%= render service, server: @server %>
    </div>
  <% end %>
</div>

app/views/services/status.js.erb
<% if @server.service_status(@service) == "installing" %>
    new ServerPoller("<%= status_server_service_path(@server, @service) %>").poll();
<% else %>
    var service = $("#<%= dom_id(@service) %>");
    service.find("[data-service-status~=installing]").addClass("is-hidden");
    service.find("[data-service-status~=installed]").removeClass("is-hidden");
    service.find(".panel").removeClass("service-installing").addClass("service-installed");
<% end %>