config/routes.rb
require "sidekiq/web"
require 'sidekiq/cron/web'
require "user_constraint"

Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq", constraints: UserConstraint.new
  root to: "servers#index"

  get "welcome" => "onboarding#index", as: "welcome"
  post "welcome" => "onboarding#create"
  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create"
  get "two_factor" => "two_factor_auths#new", as: "two_factor"
  post "two_factor" => "two_factor_auths#create"
  delete "logout" => "sessions#destroy", as: "logout"

  resources :user_activation, only: [:edit, :update]
  resources :users, only: [:index, :create, :destroy] do
    collection do
      resource :two_step_verification, only: [:new, :create, :show, :destroy], module: "users"
    end
    post :resend_activation_mail, on: :member
  end

  resources :servers, only: [:create, :show, :destroy] do
    get :test_ssh, on: :member
    get :check_installation, on: :member
    get :updating, on: :member
    get :manual_update, on: :member
    post :start_installation, on: :member
    post :start_update, on: :member
    resource :health_check, only: [:create]
    resources :apps, only: [:index, :new, :create, :destroy, :show] do
      resources :services, controller: "app_services", only: :index do
        post :create, on: :member
      end
      resources :env_vars, only: [:index, :create, :destroy]
      resources :domains, only: [:index, :create, :destroy]
      resources :backups, only: [:index, :create] do
        post :enable, on: :collection
        get :status, on: :member
      end
    end
    resources :services, only: [:index] do
      post :create, on: :member
      get :status, on: :member
    end
    resources :deploy_keys, only: [:index, :new, :create, :destroy]
  end

  # Help
  get 'help'                  => 'help#index'
  get 'help/:category/:file'  => 'help#show', as: :help_page, constraints: { category: /.*/, file: /[^\/\.]+/ }

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/controllers/app_services_controller.rb
class AppServicesController < ServerBaseController
  def index
    @app = server.apps.find(params[:app_id])
  end

  def create
    @app = Server.find(params[:server_id]).apps.find(params[:app_id])
    @service = Service.find(params[:id])
    @app.services << @service

    LinkServiceToAppJob.perform_later(@app, @service)
    redirect_to server_app_path(@app.server, @app)
  end
end

app/views/app_services/_service.html.erb
<%= content_tag :div, id: dom_id(service), class: "service" do %>
  <div class="box">
    <h3 class="subtitle"><%= service.name %></h3>
    <p class="has-text-centered">
      <%= image_tag "services/#{service.name.downcase}.png", width: 100, height: 100 %>
    </p>
    <% if app.service?(service) %>
      <p class="has-text-centered"><span class="tag is-success">Linked</span></p>
    <% else %>
      <p class="has-text-centered"><%= link_to "Link #{service.name}", server_app_service_path(app.server, app, service),
        method: :post, class: "button is-primary" %></p>
    <% end %>
  </div>
<% end %>

app/views/app_services/index.html.erb
<%= render "apps/heading", app: @app, tab: "services" %>
<% if @app.server.services.empty? %>
  <div class="has-text-centered content">
    <p>This server does not have any services installed.</p>
    <p><%= link_to "Install a service", server_services_path(@app.server), class: "button is-primary" %>
  </div>
<% else %>
  <div class="services">
    <div class="columns">
    <%= render partial: "app_services/service", collection: @app.server.services,
      locals: { app: @app } %>
    </div>
  </div>
<% end %>