config/routes.rb
require "sidekiq/web"
require 'sidekiq/cron/web'
require "user_constraint"

Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq", constraints: UserConstraint.new
  root to: "servers#index"

  get "welcome" => "onboarding#index", as: "welcome"
  post "welcome" => "onboarding#create"
  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create"
  get "two_factor" => "two_factor_auths#new", as: "two_factor"
  post "two_factor" => "two_factor_auths#create"
  delete "logout" => "sessions#destroy", as: "logout"

  resources :user_activation, only: [:edit, :update]
  resources :users, only: [:index, :create, :destroy] do
    collection do
      resource :two_step_verification, only: [:new, :create, :show, :destroy], module: "users"
    end
    post :resend_activation_mail, on: :member
  end

  resources :servers, only: [:create, :show, :destroy] do
    get :test_ssh, on: :member
    get :check_installation, on: :member
    get :updating, on: :member
    get :manual_update, on: :member
    post :start_installation, on: :member
    post :start_update, on: :member
    resource :health_check, only: [:create]
    resources :apps, only: [:index, :new, :create, :destroy, :show] do
      resources :services, controller: "app_services", only: :index do
        post :create, on: :member
      end
      resources :env_vars, only: [:index, :create, :destroy]
      resources :domains, only: [:index, :create, :destroy]
      resources :backups, only: [:index, :create] do
        post :enable, on: :collection
        get :status, on: :member
      end
    end
    resources :services, only: [:index] do
      post :create, on: :member
      get :status, on: :member
    end
    resources :deploy_keys, only: [:index, :new, :create, :destroy]
  end

  # Help
  get 'help'                  => 'help#index'
  get 'help/:category/:file'  => 'help#show', as: :help_page, constraints: { category: /.*/, file: /[^\/\.]+/ }

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/server.rb
class Server < ActiveRecord::Base
  has_many :apps, dependent: :destroy
  has_many :active_services, dependent: :destroy
  has_many :services, through: :active_services
  has_many :deploy_keys, dependent: :destroy

  before_create :create_rsa_key

  enum status: { fresh: 0, connected: 10, installing: 20, up: 30, down: 40 }

  validates :name, :ip, presence: true

  def service?(service)
    services.include?(service)
  end

  def service(service)
    active_services.find_by!(service: service)
  end

  def service_status(service)
    if service?(service)
      service(service).status
    else
      "new"
    end
  end

  def up_to_date?
    VersionParser.parse(dokku_version) == VersionParser.parse(latest_dokku_version)
  end

  def latest_dokku_version
    "v0.5.6".freeze
  end

  private

  def create_rsa_key
    key = OpenSSL::PKey::RSA.new(1024)
    self.rsa_key_public = key.public_key.to_pem
    self.rsa_key_private = key.to_pem
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  def index
    @servers = Server.all.order(created_at: :desc)
    @server = Server.new
  end

  def show
    @server = Server.find(params[:id])
    case @server.status
    when "fresh", "connected"
      @ssh_key = SSHKey.new(@server.rsa_key_private, comment: "Intercity").ssh_public_key
      render "servers/show/add_ssh"
    when "installing"
      render "servers/show/installing"
    when "up"
      redirect_to server_apps_path(@server)
    when "down"
      render "servers/show/down"
    end
  end

  def create
    @server = Server.new(server_params)
    @server.save
  end

  def test_ssh
    @server = Server.find(params[:id])
    begin
      output = SshExecution.new(@server).execute(command: "sudo ls")
      if output =~ /sudo/
        @error = "We can connect, but don't have sudo access"
        @connected = false
      else
        @connected = true
        @server.update(status: "connected")
      end
    rescue Net::SSH::ConnectionTimeout, Net::SSH::AuthenticationFailed, Errno::EHOSTUNREACH,
           Errno::ECONNREFUSED, Errno::EHOSTDOWN
      @connected = false
    end
  end

  def check_installation
    @server = Server.find(params[:id])
  end

  def start_installation
    @server = Server.find(params[:id])
    if @server.connected?
      InstallServerJob.perform_later(@server)
      @server.update(status: "installing")
    end
    redirect_to server_path(@server)
  end

  def start_update
    @server = Server.find(params[:id])
    if VersionParser.parse(@server.dokku_version) < VersionParser.parse("v0.4.11")
      redirect_to manual_update_server_path(@server)
    else
      unless @server.updating?
        UpdateServerJob.perform_later(@server)
        @server.update(updating: true)
      end

      redirect_to updating_server_path(@server)
    end
  end

  def updating
    @server = Server.find(params[:id])
  end

  def manual_update
    @server = Server.find(params[:id])
  end

  def destroy
    @server = Server.find(params[:id])
    @server.destroy
    redirect_to root_path
  end

  private

  def server_params
    params.require(:server).permit(:name, :ip)
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/show/add_ssh.html.erb
<div class="columns servers">
  <div class="column is-8 is-offset-2">
    <h1 class="title">Setup for <%= @server.name %></h1>
    <p>You need to add the following public SSH key to the "root" user of the server</p>
    <div class="ssh-key highlight">
      <button class="copy" data-clipboard-target="pre#sshkey">Copy</button>
      <pre id="sshkey"><%= @ssh_key %></pre>
    </div>
    <div class="box has-text-centered <%= "is-hidden" if @server.connected? %>" data-server-status="checking">
      <p><i class="fa fa-circle-o-notch fa-spin"></i> Checking for the SSH key</p>
      <p class="hint is-hidden"></p>
    </div>
    <div class="box has-text-centered <%= "is-hidden" unless @server.connected? %>" data-server-status="connected">
      <p>Server is up and we can connect to it!</p>
      <%= link_to "Proceed with installation", start_installation_server_path(@server), method: :post, class: "button is-primary" %>
    </div>
  </div>
</div>
<script>
  <% if @server.fresh? %>
    var poller = new ServerPoller("<%= test_ssh_server_path(@server) %>");
    poller.poll();
  <% end %>
</script>

app/views/servers/show/down.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center" data-server-status="down">
    <h1>Server <%= @server.name %> seems to be down</h1>
    <p>We could not connect to your server during the last healthcheck.</p>
    <p>Please check if the server is still online and accepting connections</p>
    <p>We keep checking this server every 30 minutes to see if it comes online.</p>
    <div class="well">
      <%= link_to "Force healthcheck", server_health_check_path(@server), method: :post, remote: true,
        class: "btn btn-default", data: { behaviour: "perform-health-check" } %>
      <p data-behaviour="performing-health-check" class="hidden"><%= icon "circle-o-notch fa-spin" %> Performing healthcheck</p>
    </div>
  </div>
  <div class="col-md-6 col-md-offset-3 text-center hidden" data-server-status="up">
    <h1>Server <%= @server.name %> is back online!</h1>
    <div class="well">
      <%= link_to "Go to server", server_path(@server), class: "btn btn-default" %>
    </div>
  </div>
</div>

app/views/servers/show/installing.html.erb
<div class="columns servers">
  <div class="column is-8 is-offset-2">
    <h1 class="title">Setup for <%= @server.name %></h1>
    <div class="<%= "is-hidden" if @server.up? %>" data-server-status="checking">
      <p>We are installing your server. This can take around 10 minutes</p>
      <div class="box">
        <div class="columns">
          <div class="column is-half is-offset-one-quarter installing">
            <div class="step step1 is-info">
              <div class="column is-2"><%= icon "circle-o-notch fa-spin" %></div>
              <div class="column auto">Updating packages</div>
            </div>
            <div class="step step2">
              <div class="column is-2"><%= icon "square-o" %></div>
              <div class="column auto">Installing Docker</div>
            </div>
            <div class="step step3">
              <div class="column is-2"><%= icon "square-o" %></div>
              <div class="column auto">Installing Dokku</div>
            </div>
            <div class="step step4">
              <div class="column is-2"><%= icon "square-o" %></div>
              <div class="column auto">Importing base image</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="box has-text-centered <%= "is-hidden" unless @server.up? %>" data-server-status="connected">
      <p>The server is installed and ready to go!</p>
      <%= link_to "Add your first app", server_path(@server), class: "button is-primary" %>
    </div>
  </div>
</div>

<script>
  <% if @server.installing? %>
    var poller = new ServerPoller("<%= check_installation_server_path(@server) %>");
    poller.poll();
  <% end %>
</script>