config/routes.rb
require "sidekiq/web"
require 'sidekiq/cron/web'
require "user_constraint"

Rails.application.routes.draw do

  mount Sidekiq::Web => "/sidekiq", constraints: UserConstraint.new
  root to: "servers#index"

  get "welcome" => "onboarding#index", as: "welcome"
  post "welcome" => "onboarding#create"
  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create"
  get "two_factor" => "two_factor_auths#new", as: "two_factor"
  post "two_factor" => "two_factor_auths#create"
  delete "logout" => "sessions#destroy", as: "logout"

  resources :user_activation, only: [:edit, :update]
  resources :users, only: [:index, :create, :destroy] do
    collection do
      resource :two_step_verification, only: [:new, :create, :show, :destroy], module: "users"
    end
    post :resend_activation_mail, on: :member
  end

  resources :servers, only: [:create, :show, :destroy] do
    get :test_ssh, on: :member
    get :check_installation, on: :member
    get :updating, on: :member
    get :manual_update, on: :member
    post :start_installation, on: :member
    post :start_update, on: :member
    resource :health_check, only: [:create]
    resources :apps, only: [:index, :new, :create, :destroy, :show] do
      resources :services, controller: "app_services", only: :index do
        post :create, on: :member
      end
      resources :env_vars, only: [:index, :create, :destroy]
      resources :domains, only: [:index, :create, :destroy]
      resources :backups, only: [:index, :create] do
        post :enable, on: :collection
        get :status, on: :member
      end
    end
    resources :services, only: [:index] do
      post :create, on: :member
      get :status, on: :member
    end
    resources :deploy_keys, only: [:index, :new, :create, :destroy]
  end

  # Help
  get 'help'                  => 'help#index'
  get 'help/:category/:file'  => 'help#show', as: :help_page, constraints: { category: /.*/, file: /[^\/\.]+/ }

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/views/apps/_app.html.erb
<%= content_tag :div, id: dom_id(app), class: "app" do %>
  <div class="card">
    <header class="card-header">
      <p class="card-header-title"><%= link_to app.name, server_app_path(app.server, app) %></p>
    </header>
    <div class="card-content">
      <p><strong>Domain(s):</strong> <%= app.domains.pluck(:name).join(", ").presence || "-" %></p>
      <p><strong>Deploy URL:</strong> dokku@<%= app.server.ip %>:<%= app.clean_name %></p>
      <p><strong>Services:</strong>
      <% app.services.each do |service| %>
        <span class="tag label-primary"><%= service.name %></span>
      <% end %>
      <p><strong>Backups:</strong>
      <% if app.backups_enabled? %>
        <span class="tag is-success">Enabled</span></p>
      <% else %>
        <span class="tag is-danger">Disabled</span></p>
      <% end %>
    </div>
    <div class="card-footer">
      <%= link_to icon("trash"), server_app_path(app.server, app),
        data: { confirm: "Are you REALLY sure?" }, class: "text-danger card-footer-item", method: :delete %>
    </div>
  </div>
<% end %>

app/views/apps/_heading.html.erb
<div class="heading">
  <h1 class="title is-center has-text-centered"><%= app.name %></h1>
  <div class="tabs is-centered">
    <ul>
      <li><%= link_to "Server".html_safe, server_apps_path(app.server) %></li>
      <li class="<%= "is-active" if tab == "info" %>"><%= link_to "Info", server_app_path(app.server, app) %></li>
      <li class="<%= "is-active" if tab == "domains" %>"><%= link_to "Domains", server_app_domains_path(app.server, app) %></li>
      <li class="<%= "is-active" if tab == "services" %>"><%= link_to "Linked services", server_app_services_path(app.server, app) %></li>
      <li class="<%= "is-active" if tab == "env_vars" %>"><%= link_to "Environment vars", server_app_env_vars_path(app.server, app) %></li>
      <li class="<%= "is-active" if tab == "backups" %>"><%= link_to "Backups", server_app_backups_path(app.server, app) %></li>
    </ul>
  </div>
</div>
<%= render "flashes" -%>

app/views/apps/index.html.erb
<%= render "servers/heading", server: @server, tab: "apps" %>
<div class="apps">
  <% @apps.each_slice(3).each do |apps| %>
    <div class="columns">
      <%= render apps %>
    </div>
  <% end %>
  <div class="add-app">
      <%= link_to "#{icon "plus"} New app".html_safe, new_server_app_path(@server),
        data: { behaviour: "new-app" }, class: "button is-success is-large" %>
  </div>
</div>

app/views/apps/new.html.erb
<div class="columns">
  <div class="column is-4 is-offset-4">
    <h1 class="title">Add new app to <%= @app.server.name %></h1>
    <%= form_for [@app.server, @app] do |f| %>
      <%= f.text_field :name, class: "input control", placeholder: "Name" %>
      <%= f.submit "Create app", class: "button control is-primary" %>
    <% end %>
  </div>
</div>

app/views/apps/show.html.erb
<%= render "apps/heading", app: @app, tab: "info" %>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <tr>
        <th style="width: 20%">Name</th>
        <td><%= @app.name %></td>
        <td class="actions"></td>
      </tr>
      <tr>
        <th style="width: 20%">Deploy URL</th>
        <td>dokku@<%= @app.server.ip %>:<%= @app.clean_name %></td>
        <td></td>
      </tr>
      <tr>
        <th>Domain(s)</th>
        <td><%= @app.domains.pluck(:name).join(", ").presence || "-" %></td>
        <td><%= link_to "Change", server_app_domains_path(@app.server, @app) %></td>
      </tr>
      <tr>
        <th>Active services</th>
        <td><%= @app.services.map(&:name).join(", ").presence || "None" %></td>
        <td><%= link_to "Change", server_app_services_path(@app.server, @app) %></td>
      </tr>
      <%# <tr> %>
      <%#   <th>SSL active</th> %>
      <%#   <td><span class="label label-danger">No</span></td> %>
      <%#   <td><%= link_to "Enable SSL", "#" %1></td> %>
      <%# </tr> %>
    </table>
  </div>
</div>